[package]
name = "sakiot-dsp"
version.workspace = true
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
wasm = ["dep:js-sys", "dep:wasm-bindgen"]

[dependencies]
libm = "=0.2.16"
js-sys = { version = "=0.3.99", optional = true }
wasm-bindgen = { version = "=0.2.122", optional = true }

[lints]
workspace = true
