use utoipa::{
    Modify, OpenApi,
    openapi::security::{ApiKey, ApiKeyValue, SecurityScheme},
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "sakiot web_server",
        description = "HTTP + WS API for the sakiot Discord bot stack.",
        version = "0.1.0",
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "auth", description = "Discord OAuth, JWT refresh, logout"),
        (name = "user", description = "Current user + guild membership"),
        (name = "audio", description = "Recording listing, processing, and event metadata"),
        (name = "media", description = "Durable media job status and results"),
        (name = "clips", description = "Voice clip CRUD and playback"),
        (name = "stamps", description = "Guild stamp metadata"),
        (name = "admin", description = "Guild admin configuration"),
    ),
    paths(
        // Intentionally undocumented: /api/dev_login (dev-login feature only),
        // the /livez, /readyz and /healthz probes, and
        // /internal/fbi-agent/grpc-endpoints (outside /api; accepts loopback
        // or shared-secret requests from the deploy engine, not a client API).
        crate::admin::cooldowns::delete_user_override,
        crate::admin::cooldowns::get_guild_cooldown,
        crate::admin::cooldowns::list_user_overrides,
        crate::admin::cooldowns::set_guild_cooldown,
        crate::admin::cooldowns::set_user_override,
        crate::admin::voice_settings::delete_voice_settings,
        crate::admin::voice_settings::get_voice_settings,
        crate::admin::voice_settings::put_voice_settings,
        crate::admin::recording_policy::get_recording_policy,
        crate::admin::recording_policy::put_recording_policy,
        crate::audio::events::get_recording_events,
        crate::audio::listing::get_current_month_permission,
        crate::audio::listing::get_live_stems,
        crate::audio::listing::get_session_listing_entry,
        crate::audio::live::live_playlist,
        crate::audio::live::live_segment,
        crate::audio::live::live_state,
        crate::audio::peaks::get_clip_waveform_data,
        crate::audio::peaks::get_waveform_data,
        crate::audio::serve::download_audio,
        crate::audio::serve::get_audio,
        crate::audio::silence::remove_silence,
        crate::audio::sessions::create_session_clip,
        crate::audio::sessions::download_session,
        crate::audio::sessions::get_session_events,
        crate::audio::sessions::get_session_manifest,
        crate::audio::sessions::get_session_channel_mix,
        crate::audio::sessions::generate_session_channel_mix,
        crate::audio::sessions::get_session_channel_mix_media,
        crate::audio::sessions::get_session_segment,
        crate::audio::sessions::get_session_silence_free,
        crate::audio::sessions::get_session_silence_free_waveform,
        crate::audio::sessions::get_session_silence_removal_status,
        crate::audio::sessions::get_session_waveform,
        crate::audio::sessions::rebuild_session_waveform,
        crate::audio::sessions::rebuild_session_silence_free_waveform,
        crate::audio::sessions::remove_session_silence,
        crate::audio::sessions::session_live_playlist,
        crate::audio::sessions::session_live_segment,
        crate::auth::handlers::discord_login,
        crate::auth::handlers::oauth_start,
        crate::auth::handlers::refresh_jwt,
        crate::auth::handlers::logout,
        crate::clip_editor::compose_clip,
        crate::clip_editor::compose_clip_status,
        crate::clips::create_clip,
        crate::clips::delete,
        crate::clips::get_clip,
        crate::clips::get_clips,
        crate::clips::play_clip,
        crate::clips::rename_clip,
        crate::members::get_guild_roles,
        crate::members::get_role_members,
        crate::members::get_role_view,
        crate::media_jobs::get_media_job,
        crate::media_jobs::get_media_job_result,
        crate::recording_deletion::delete_recording,
        crate::recording_deletion::get_recording_deletion,
        crate::stamps::get_stamps,
        crate::user::get_current_user,
        crate::user::get_current_user_guilds,
        crate::recording_opt_out::get_recording_opt_out,
        crate::recording_opt_out::put_recording_opt_out,
    ),
    components(schemas(
        crate::admin::cooldowns::CooldownBody,
        crate::admin::cooldowns::GuildCooldown,
        crate::admin::cooldowns::UserOverride,
        crate::admin::voice_settings::GuildVoiceSettings,
        crate::admin::voice_settings::GuildVoiceSettingsBody,
        crate::admin::recording_policy::GuildRecordingPolicy,
        crate::admin::recording_policy::GuildRecordingPolicyBody,
        crate::admin::recording_policy::VoiceChannel,
        crate::audio::events::VoiceEventDto,
        crate::audio::live::StateResponse,
        crate::audio::silence::RemoveSilenceResponse,
        crate::audio::types::Channels,
        crate::audio::types::Directories,
        crate::audio::types::File,
        crate::audio::types::StartEnd,
        crate::audio::sessions::SessionDownloadQuery,
        crate::audio::sessions::ChannelMixQuery,
        crate::audio::sessions::ChannelMixMediaQuery,
        crate::audio::sessions::ChannelMixScope,
        crate::audio::sessions::ChannelMixParticipant,
        crate::audio::sessions::ChannelMixParticipantSettings,
        crate::audio::sessions::ChannelMixGenerationSettings,
        crate::audio::sessions::ChannelMixSourceSegment,
        crate::audio::sessions::ChannelMixTrack,
        crate::audio::sessions::GenerateChannelMixBody,
        crate::audio::sessions::ChannelMixReason,
        crate::audio::sessions::ChannelMixResponse,
        crate::audio::sessions::ChannelMixStatus,
        crate::audio::sessions::SessionManifestDto,
        crate::audio::sessions::SessionSegmentDto,
        crate::audio::sessions::SilenceFreeSessionResponse,
        crate::audio::sessions::SessionTimelineEventDto,
        crate::audio::sessions::SessionWaveformResponse,
        crate::auth::handlers::RefreshTokenResponse,
        crate::clip_editor::ComposeClipAccepted,
        crate::clip_editor::ComposeClipBody,
        crate::clip_editor::ComposeClipStatus,
        crate::clip_editor::ComposeSegment,
        crate::clip_editor::AdvancedSegmentEffectsDto,
        crate::clip_editor::SegmentEffectsDto,
        crate::clips::ClipInfo,
        crate::clips::CreateClipResponse,
        crate::clips::RenameClipBody,
        crate::errors::ApiError,
        crate::members::GuildRole,
        crate::members::RoleChannel,
        crate::members::RoleMember,
        crate::members::RoleView,
        crate::media_jobs::MediaJobStatus,
        crate::recording_deletion::RecordingDeletionStatus,
        crate::recording_opt_out::RecordingOptOut,
        crate::stamps::StampInfo,
        crate::user::GuildDataForFrontEnd,
        crate::user::UserDataForFrontEnd,
    )),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "access_token",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new(
                "__Host-sakiot-access_token",
            ))),
        );
        components.add_security_scheme(
            "csrf_token",
            SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-CSRF-Token"))),
        );
    }
}
