/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/admin/guilds/{guild_id}/cooldown": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_guild_cooldown"];
		put: operations["set_guild_cooldown"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/cooldown/overrides": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_user_overrides"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/cooldown/overrides/{user_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["set_user_override"];
		post?: never;
		delete: operations["delete_user_override"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_guild_roles"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/roles/{role_id}/channels": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_role_view"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/roles/{role_id}/members": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_role_members"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/guilds/{guild_id}/voice-settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_voice_settings"];
		put: operations["put_voice_settings"];
		post?: never;
		delete: operations["delete_voice_settings"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/create/{guild_id}/{channel_id}/{year}/{month}/{file_name}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["create_clip"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/{guild_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_clips"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/{guild_id}/compose": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["compose_clip"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/{guild_id}/compose/{clip_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["compose_clip_status"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/clips/{guild_id}/{clip_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["rename_clip"];
		post?: never;
		delete: operations["delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/events/{guild_id}/{channel_id}/{year}/{month}/{stem}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Voice state events (mute/deafen/etc.) overlapping the recording window for
		 *     `{stem}`. Frontend uses `offset_ms` against the audio element's currentTime
		 *     to render markers / current-state badges on the timeline.
		 * @description Bounds: [start_ts, COALESCE(end_ts, now())]. start_ts/end_ts are stored as
		 *     epoch-ms BIGINTs on `audio_files`; voice_state_events.occurred_at is
		 *     TIMESTAMPTZ — converted via `to_timestamp(ms / 1000.0)` for the range scan.
		 */
		get: operations["get_recording_events"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/live/{guild_id}/{channel_id}/{year}/{month}/{stem}/state": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["live_state"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/clips": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["create_session_clip"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/download": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["download_session"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/events": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_session_events"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/manifest": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_session_manifest"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/remove-silence": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_session_silence_removal_status"];
		put?: never;
		post: operations["remove_session_silence"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/silence-free": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_session_silence_free"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/silence-free/waveform": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_session_silence_free_waveform"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/silence-free/waveform/rebuild": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["rebuild_session_silence_free_waveform"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/waveform": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_session_waveform"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/audio/sessions/{recording_session_id}/waveform/rebuild": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["rebuild_session_waveform"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/current/{guild_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_current_month_permission"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/current/{guild_id}/live-stems": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Live recordings for a guild, filtered to the channels the caller has read
		 *     access to. A recording is live only if its unfinished row has a fresh
		 *     recording heartbeat from a fresh, non-stopped bot instance.
		 */
		get: operations["get_live_stems"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["refresh_jwt"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/remove_silence/{guild_id}/{channel_id}/{year}/{month}/{file_name}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["remove_silence"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/stamps/{guild_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_stamps"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/current": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_current_user"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/users/current/guilds": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_current_user_guilds"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApiError: {
			/** Format: int32 */
			code: number;
			message: string;
		};
		Channels: {
			channel_id: string;
			dirs: components["schemas"]["Directories"][];
		};
		ClipInfo: {
			/** @example 146638124288704513 */
			channel_id: string;
			clip_id: string;
			/**
			 * @description Serialized clip editor edit for composed clips; re-importable into the
			 *     editor. Null for clips cut from a single recording.
			 */
			composition?: unknown;
			/** @example 146638124288704513 */
			guild_id: string;
			/** Format: float */
			length?: number | null;
			name?: string | null;
			original_file_name?: string | null;
			recording_session_id?: string | null;
			saved_file_name?: string | null;
			silence_free: boolean;
			/** Format: int64 */
			size?: number | null;
			/** Format: float */
			start_time: number;
			/** @example 146638124288704513 */
			user_id: string;
		};
		ComposeClipAccepted: {
			id: string;
			/** Format: int32 */
			progress: number;
			status: string;
		};
		ComposeClipBody: {
			/** Format: float */
			master_volume_db: number;
			name?: string | null;
			segments: components["schemas"]["ComposeSegment"][];
		};
		ComposeClipStatus: {
			/** Format: int32 */
			progress: number;
			status: string;
		};
		ComposeSegment: {
			effects: components["schemas"]["SegmentEffectsDto"];
			source: string;
			source_id: string;
			/** Format: float */
			source_in: number;
			/** Format: float */
			source_out: number;
			/** Format: float */
			timeline_start: number;
			/** Format: int32 */
			track: number;
		};
		CooldownBody: {
			/** Format: int32 */
			cooldown_seconds: number;
		};
		CreateClipResponse: {
			file: string;
			id: string;
			name: string;
			status: string;
		};
		Directories: {
			months?: null | components["schemas"]["HashMap"];
			/** Format: int32 */
			year: number;
		};
		File: {
			/**
			 * @description Role-preview annotation only: "can-listen" | "visible-only" | "hidden".
			 *     Absent in normal listings, which are filtered to what the viewer can
			 *     actually play.
			 */
			access?: string | null;
			channel_journey?: string[] | null;
			display_name?: string | null;
			file: string;
			recording_session_id?: string | null;
			state?: string | null;
			user_id?: string | null;
		};
		GuildCooldown: {
			/** Format: int32 */
			cooldown_seconds: number;
		};
		GuildDataForFrontEnd: {
			icon?: string | null;
			/** @example 146638124288704513 */
			id: string;
			name: string;
			owner: boolean;
			/** @example 268435456 */
			permissions: string;
		};
		GuildRole: {
			/** Format: int64 */
			member_count: number;
			name: string;
			/** @example 268435456 */
			permission: string;
			/** @example 146638124288704513 */
			role_id: string;
		};
		GuildVoiceSettings: {
			is_default: boolean;
			/** Format: int32 */
			pending_cap_seconds: number;
		};
		GuildVoiceSettingsBody: {
			/** Format: int32 */
			pending_cap_seconds: number;
		};
		HashMap: {
			[key: string]:
				| null
				| {
						/**
						 * @description Role-preview annotation only: "can-listen" | "visible-only" | "hidden".
						 *     Absent in normal listings, which are filtered to what the viewer can
						 *     actually play.
						 */
						access?: string | null;
						channel_journey?: string[] | null;
						display_name?: string | null;
						file: string;
						recording_session_id?: string | null;
						state?: string | null;
						user_id?: string | null;
				  }[];
		};
		RefreshTokenError: {
			error: string;
			message: string;
		};
		RefreshTokenResponse: {
			status: string;
		};
		RemoveSilenceResponse: {
			message: string;
			url: string;
		};
		RenameClipBody: {
			name: string;
		};
		RoleChannel: {
			can_join: boolean;
			/** @example 146638124288704513 */
			channel_id: string;
			name: string;
		};
		RoleMember: {
			name?: string | null;
			/** @example 146638124288704513 */
			user_id: string;
		};
		RoleView: {
			can_manage_guild: boolean;
			channels: components["schemas"]["RoleChannel"][];
			/** @example 1024 */
			permission: string;
		};
		SegmentEffectsDto: {
			/** Format: float */
			bass_db: number;
			/** Format: float */
			pitch_cents: number;
			/** Format: float */
			rate: number;
			/** Format: float */
			treble_db: number;
			/** Format: float */
			volume_db: number;
		};
		SessionDownloadQuery: {
			/** Format: double */
			end?: number | null;
			remove_silence?: boolean | null;
			/** Format: double */
			start?: number | null;
		};
		SessionManifestDto: {
			channel_journey: string[];
			current_channel_id?: string | null;
			/** Format: int64 */
			duration_ms: number;
			/** Format: int64 */
			ended_at_ms?: number | null;
			events: components["schemas"]["SessionTimelineEventDto"][];
			guild_id: string;
			recording_session_id: string;
			segments: components["schemas"]["SessionSegmentDto"][];
			/** Format: int64 */
			started_at_ms: number;
			starting_channel_id: string;
			state: string;
			user_id: string;
		};
		SessionSegmentDto: {
			audio_file_id?: string | null;
			channel_id?: string | null;
			/** Format: int64 */
			end_ms: number;
			file_name?: string | null;
			from_channel_id?: string | null;
			hls_playlist_url?: string | null;
			kind: string;
			media_url?: string | null;
			reason?: string | null;
			/** Format: int32 */
			segment_index?: number | null;
			/** Format: int64 */
			start_ms: number;
			to_channel_id?: string | null;
		};
		SessionTimelineEventDto: {
			channel_id?: string | null;
			details: unknown;
			event_type: string;
			/** Format: int64 */
			offset_ms: number;
			previous_channel_id?: string | null;
			source: string;
		};
		SessionWaveformResponse: {
			building: boolean;
			data?: string | null;
			/** Format: int32 */
			progress: number;
		};
		SilenceFreeSessionResponse: {
			/** Format: int32 */
			progress: number;
			status: string;
		};
		StampInfo: {
			/** Format: int64 */
			audio_file_id?: number | null;
			audio_url?: string | null;
			/** @example 146638124288704513 */
			channel_id: string;
			channel_name?: string | null;
			/** Format: date-time */
			created_at: string;
			file_name?: string | null;
			/** @example 146638124288704513 */
			guild_id: string;
			/** Format: int64 */
			id: number;
			/** Format: int32 */
			month?: number | null;
			note?: string | null;
			/** Format: int32 */
			offset_ms: number;
			recording_session_id?: string | null;
			/** Format: int32 */
			segment_index?: number | null;
			/** Format: int64 */
			session_fragment_count?: number | null;
			/** Format: int64 */
			session_started_at_ms?: number | null;
			/** Format: int64 */
			stamp_ts: number;
			stamper_name?: string | null;
			/** @example 146638124288704513 */
			stamper_user_id: string;
			/** Format: int64 */
			start_ts?: number | null;
			target_name?: string | null;
			/** @example 146638124288704513 */
			target_user_id: string;
			waveform_url?: string | null;
			/** Format: int32 */
			year?: number | null;
		};
		StartEnd: {
			/** Format: float */
			end?: number | null;
			name?: string | null;
			silence_free?: boolean | null;
			/** Format: float */
			start?: number | null;
		};
		StateResponse: {
			/** Format: int64 */
			ended_at?: number | null;
			live: boolean;
			/** Format: int64 */
			started_at?: number | null;
		};
		UserDataForFrontEnd: {
			avatar: string;
			email?: string | null;
			/** Format: int32 */
			flags?: number | null;
			is_dev: boolean;
			/** Format: int32 */
			public_flags?: number | null;
			/** @example 146638124288704513 */
			user_id: string;
			username: string;
		};
		UserOverride: {
			/** Format: int32 */
			cooldown_seconds: number;
			/** Format: date-time */
			updated_at: string;
			/** Format: int64 */
			user_id: number;
		};
		VoiceEventDto: {
			channel_id?: string | null;
			event_type: string;
			/** Format: int64 */
			offset_ms: number;
			user_id: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_guild_cooldown: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guild cooldown */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildCooldown"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	set_guild_cooldown: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CooldownBody"];
			};
		};
		responses: {
			/** @description Guild cooldown updated */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid cooldown */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	list_user_overrides: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User cooldown overrides */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserOverride"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	set_user_override: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord user id */
				user_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CooldownBody"];
			};
		};
		responses: {
			/** @description User cooldown override updated */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid cooldown */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	delete_user_override: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord user id */
				user_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description User cooldown override deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_guild_roles: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guild roles with member counts */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildRole"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_role_view: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord role id */
				role_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description What a member with only this role can see */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RoleView"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Role does not exist in this guild */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_role_members: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord role id */
				role_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Members holding the role */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RoleMember"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description User cannot manage this guild */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Role does not exist in this guild */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_voice_settings: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Effective guild voice settings */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildVoiceSettings"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Manage Guild required */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	put_voice_settings: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["GuildVoiceSettingsBody"];
			};
		};
		responses: {
			/** @description Updated guild voice settings */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildVoiceSettings"];
				};
			};
			/** @description Pending cap below 60 seconds */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Manage Guild required */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	delete_voice_settings: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Default guild voice settings restored */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildVoiceSettings"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Manage Guild required */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	create_clip: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				file_name: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StartEnd"];
			};
		};
		responses: {
			/** @description Clip created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreateClipResponse"];
				};
			};
			/** @description Invalid clip request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_clips: {
		parameters: {
			query: {
				/** @description Impersonate a guild role (managers only) */
				as_role: number;
			};
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guild clips */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ClipInfo"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing guild or channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Role does not exist in this guild */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	compose_clip: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ComposeClipBody"];
			};
		};
		responses: {
			/** @description Clip composition started */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ComposeClipAccepted"];
				};
			};
			/** @description Invalid composition request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Source clip not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	compose_clip_status: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Composition clip id */
				clip_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Composition status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ComposeClipStatus"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	rename_clip: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Clip id */
				clip_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RenameClipBody"];
			};
		};
		responses: {
			/** @description Clip renamed */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Invalid clip name */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Not clip owner or guild manager */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Clip not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Clip id */
				clip_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Clip deleted */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Not clip owner or guild manager */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Clip not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_recording_events: {
		parameters: {
			query?: {
				/** @description Optional user id filter */
				user_id?: number;
			};
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				stem: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Voice events for recording */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VoiceEventDto"][];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Recording not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	live_state: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				stem: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Live recording state */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StateResponse"];
				};
			};
			/** @description Invalid stem */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	create_session_clip: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StartEnd"];
			};
		};
		responses: {
			/** @description Cross-fragment clip created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreateClipResponse"];
				};
			};
			/** @description Clip must be 1-20 seconds */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Composition failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	download_session: {
		parameters: {
			query?: {
				/** @description Range start in logical seconds */
				start?: number;
				/** @description Range end in logical seconds */
				end?: number;
				/** @description Run FFmpeg silence removal after composition */
				remove_silence?: boolean;
			};
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Composed Ogg/Opus download */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"audio/ogg": unknown;
				};
			};
			/** @description Invalid range */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Session not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Composition failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_session_events: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Unified logical timeline events */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionTimelineEventDto"][];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Session not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_session_manifest: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Logical recording manifest */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionManifestDto"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Session not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_session_silence_removal_status: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current silence-removal status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SilenceFreeSessionResponse"];
				};
			};
			/** @description Session is not finalized */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	remove_session_silence: {
		parameters: {
			query?: {
				/** @description Replace an existing silence-free session */
				force?: boolean;
			};
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Silence-free session is ready */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SilenceFreeSessionResponse"];
				};
			};
			/** @description Silence removal started or is already running */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SilenceFreeSessionResponse"];
				};
			};
			/** @description Session is not finalized */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Composition failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_session_silence_free: {
		parameters: {
			query?: {
				/** @description Download instead of inline playback */
				download?: boolean;
			};
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Cached silence-free Ogg/Opus */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"audio/ogg": unknown;
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Silence-free session has not been generated */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_session_silence_free_waveform: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Silence-free session waveform status and peaks */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionWaveformResponse"];
				};
			};
			/** @description Session is not finalized */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Silence-free session has not been generated */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Waveform generation failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	rebuild_session_silence_free_waveform: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Silence-free waveform rebuild started or already running */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionWaveformResponse"];
				};
			};
			/** @description Session is not finalized */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Silence-free session has not been generated */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Waveform generation failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_session_waveform: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Combined peaks; explicit gaps are zero-valued */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionWaveformResponse"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Session not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Waveform generation failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	rebuild_session_waveform: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Logical recording session id */
				recording_session_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Combined waveform rebuild started or already running */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionWaveformResponse"];
				};
			};
			/** @description Missing access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description One or more audible channels inaccessible */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Session not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Waveform generation failed */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_current_month_permission: {
		parameters: {
			query: {
				/** @description Impersonate a guild role (managers only) */
				as_role: number;
			};
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Recording tree visible to current user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Channels"][];
				};
			};
			/** @description Invalid guild id */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing guild or channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Role does not exist in this guild */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_live_stems: {
		parameters: {
			query: {
				/** @description Impersonate a guild role (managers only) */
				as_role: number;
			};
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Currently live recording stems */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": string[];
				};
			};
			/** @description Invalid guild id */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing guild or channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Role does not exist in this guild */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Cookies cleared */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid CSRF token */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	refresh_jwt: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description New access token issued */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RefreshTokenResponse"];
				};
			};
			/** @description Missing, expired, or invalid refresh token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Missing or invalid CSRF token */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	remove_silence: {
		parameters: {
			query?: never;
			header: {
				/** @description Idempotency key for processing request */
				"Idempotency-Key": string;
			};
			path: {
				/** @description Discord guild id */
				guild_id: number;
				/** @description Discord channel id */
				channel_id: number;
				/** @description Recording year */
				year: number;
				/** @description Recording month */
				month: number;
				/** @description Recording file stem */
				file_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Silence removal file exists or processing started */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RemoveSilenceResponse"];
				};
			};
			/** @description Existing processing request completed */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RemoveSilenceResponse"];
				};
			};
			/** @description Missing idempotency key */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Idempotency key reused for another request */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Concurrent processing state unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_stamps: {
		parameters: {
			query: {
				/** @description Impersonate a guild role (managers only) */
				as_role: number;
			};
			header?: never;
			path: {
				/** @description Discord guild id */
				guild_id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Recent stamps for guild */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StampInfo"][];
				};
			};
			/** @description Missing or invalid access token */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Missing guild or channel permission */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Role does not exist in this guild */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
	get_current_user: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current authenticated user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserDataForFrontEnd"];
				};
			};
			/** @description Missing or invalid access_token cookie */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Token not attached to request context */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_current_user_guilds: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Guilds visible to current user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["GuildDataForFrontEnd"][];
				};
			};
			/** @description Token not attached to request context */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiError"];
				};
			};
		};
	};
}
